### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by lokka30**
This PR creates 5 issue templates:

1. `bug-report.yml`
2. `false-negative-report.yml`
3. `false-positive-report.yml`
4. `feature-request.yml`
5. `question.yml`

This PR requires the following issue labels to be added to this repository (I can't PR this):

* `false positive` - issues describing a false positive
* `false negative` - issues describing a false negative
* `unconfirmed` - unconfirmed feature requests, bug reports or check issue reports
* `confirmed` - confirmed feature requests, bug reports or check issue reports

Test if you wish at <https://www.github.com/lokka30/Grim/issues/>.

This PR is not a draft - it's been fully tested and is ready to be merged.

### CODE REVIEW

**Comment by lokka30** [comment]
Solves #331

**Review by sadcenter — APPROVED** [review]

**Comment by lokka30** [comment]
@MWHunter

**Comment by MWHunter** [comment]
These templates seem too strict.  A video and client and server version is usually enough.

**Comment by lokka30** [comment]
> These templates seem too strict. A video and client and server version is usually enough.

Which templates would you like me to edit?

**Comment by MWHunter** [comment]
The current templates seem fine

**Pull request closed without merging**
